---
"@ponder/core": patch
---

Fixed type error for `p.many()` with self reference.
